// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OutboxNet.EntityFrameworkCore;

#nullable disable

namespace OutboxNet.SampleApp.Migrations.OutboxDb
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20260415000001_ImproveIndexes")]
    partial class ImproveIndexes
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
