// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OutboxNet.EntityFrameworkCore;

#nullable disable

namespace OutboxNet.SampleApp.Migrations.OutboxDb
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20260417103313_DropDeliveryAttemptSubscriptionFk")]
    partial class DropDeliveryAttemptSubscriptionFk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("outbox")
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("OutboxNet.Models.DeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<int>("AttemptNumber")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset>("AttemptedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<long>("DurationMs")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasDefaultValue(0L);

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("HttpStatusCode")
                        .HasColumnType("int");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<Guid>("OutboxMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ResponseBody")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<int>("Status")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("WebhookSubscriptionId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AttemptedAt")
                        .HasDatabaseName("IX_DeliveryAttempts_AttemptedAt");

                    b.HasIndex("OutboxMessageId", "WebhookSubscriptionId")
                        .HasDatabaseName("IX_DeliveryAttempts_MessageId_SubscriptionId");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("OutboxMessageId", "WebhookSubscriptionId"), new[] { "Status" });

                    b.HasIndex("WebhookSubscriptionId", "AttemptedAt")
                        .HasDatabaseName("IX_DeliveryAttempts_SubscriptionId_AttemptedAt");

                    b.ToTable("DeliveryAttempts", "outbox");
                });

            modelBuilder.Entity("OutboxNet.Models.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("EntityId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Headers")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastError")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<DateTimeOffset?>("NextRetryAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<int>("RetryCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("UserId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EventType")
                        .HasDatabaseName("IX_OutboxMessages_EventType");

                    b.HasIndex("Status", "LockedUntil")
                        .HasDatabaseName("IX_OutboxMessages_Status_LockedUntil")
                        .HasFilter("[LockedUntil] IS NOT NULL");

                    b.HasIndex("Status", "CreatedAt", "LockedUntil", "NextRetryAt")
                        .HasDatabaseName("IX_OutboxMessages_Lock_Candidate")
                        .HasFilter("[Status] IN (0, 1)");

                    SqlServerIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "CreatedAt", "LockedUntil", "NextRetryAt"), new[] { "TenantId", "UserId", "EntityId", "EventType", "RetryCount" });

                    b.HasIndex("TenantId", "UserId", "EntityId", "Status", "LockedUntil")
                        .HasDatabaseName("IX_OutboxMessages_PartitionKey_Status");

                    b.ToTable("OutboxMessages", "outbox");
                });

            modelBuilder.Entity("OutboxNet.Models.WebhookSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWSEQUENTIALID()");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)")
                        .HasDefaultValueSql("SYSDATETIMEOFFSET()");

                    b.Property<string>("CustomHeaders")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<int>("MaxRetries")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(5);

                    b.Property<string>("Secret")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)");

                    b.Property<string>("TenantId")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<int>("Timeout")
                        .HasColumnType("int")
                        .HasColumnName("TimeoutSeconds");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasPrecision(3)
                        .HasColumnType("datetimeoffset(3)");

                    b.Property<string>("WebhookUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.HasKey("Id");

                    b.HasIndex("EventType", "IsActive")
                        .HasDatabaseName("IX_WebhookSubscriptions_EventType_Active");

                    b.HasIndex("TenantId", "IsActive")
                        .HasDatabaseName("IX_WebhookSubscriptions_TenantId_Active")
                        .HasFilter("[TenantId] IS NOT NULL");

                    b.ToTable("WebhookSubscriptions", "outbox");
                });

            modelBuilder.Entity("OutboxNet.Models.DeliveryAttempt", b =>
                {
                    b.HasOne("OutboxNet.Models.OutboxMessage", "OutboxMessage")
                        .WithMany()
                        .HasForeignKey("OutboxMessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OutboxMessage");
                });
#pragma warning restore 612, 618
        }
    }
}
