// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using OutboxNet.EntityFrameworkCore;

#nullable disable

namespace OutboxNet.SampleApp.Migrations.OutboxDb
{
    [DbContext(typeof(OutboxDbContext))]
    [Migration("20260413000001_AddPartitionKeys")]
    partial class AddPartitionKeys
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
